# Thông tin kết nối Database
VAR_SQL_DRIVER = "{SQL Server Native Client 11.0}"
VAR_SERVER_NAME = "KSNB3\SQLEXPRESS"
VAR_DATABASE_NAME = "DATABASE_USER_ID"
VAR_SQL_QUERY = "select * from TB_DS_DATABASE"