# Câu lệnh query
VAR_SQL_QUERY_01 = "select * from TB_DS_DATABASE"
VAR_SQL_QUERY_02 = "select * from BADepositDetail"
VAR_SQL_QUERY_03 =  ("SELECT" + ";"
                    "[RefDate]" + ";" 
                    ",[RefNo]" + ";" 
                    ",[PostedDate]" + ";" 
                    ",[InvNo]" + ";" 
                    ",[InvDate]" + ";" 
                    ",[InvSeries]" + ";" 
                    ",[AccountObjectCode]" + ";" 
                    ",[AccountObjectName]" + ";" 
                    ",[AccountObjectTaxCode]" + ";" 
                    ",[AccountObjectAddress]" + ";" 
                    ",[InventoryItemCode]" + ";" 
                    ",[InventoryItemName]" + ";" 
                    ",[UnitPrice]" + ";" 
                    ",[Quantity]" + ";" 
                    ",[AccountNumber]" + ";" 
                    ",[CorrespondingAccountNumber]" + ";" 
                    ",[BranchID]" + ";" 
                    "FROM [TBD_2024_240409].[dbo].[AccountObjectLedger]" + ";" 
                    "order by [RefDate] DESC, [RefNo] DESC, [InvNo] DESC")