# Form implementation generated from reading ui file 'MODULE_SQL_CONNECTING.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(392, 294)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 210, 351, 31))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 91, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 91, 31))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 91, 31))
        self.label_4.setObjectName("label_4")
        self.InputBox_ServerName = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.InputBox_ServerName.setGeometry(QtCore.QRect(120, 10, 251, 31))
        self.InputBox_ServerName.setObjectName("InputBox_ServerName")
        self.InputBox_DatabaseName = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.InputBox_DatabaseName.setGeometry(QtCore.QRect(120, 60, 251, 31))
        self.InputBox_DatabaseName.setObjectName("InputBox_DatabaseName")
        self.InputBox_LoginName = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.InputBox_LoginName.setGeometry(QtCore.QRect(120, 110, 251, 31))
        self.InputBox_LoginName.setObjectName("InputBox_LoginName")
        self.InputBox_LoginPass = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.InputBox_LoginPass.setGeometry(QtCore.QRect(120, 160, 251, 31))
        self.InputBox_LoginPass.setObjectName("InputBox_LoginPass")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 91, 31))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 392, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.FcConnectToSQL)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "CONNECT"))
        self.label.setText(_translate("MainWindow", "SERVER NAME"))
        self.label_2.setText(_translate("MainWindow", "DATABASE NAME"))
        self.label_4.setText(_translate("MainWindow", "LOGIN PASS"))
        self.InputBox_ServerName.setPlainText(_translate("MainWindow", "QUANNGUYEN\\SQLEXPRESS"))
        self.InputBox_DatabaseName.setPlainText(_translate("MainWindow", "HA_NOI_2024"))
        self.InputBox_LoginName.setPlainText(_translate("MainWindow", "sa"))
        self.InputBox_LoginPass.setPlainText(_translate("MainWindow", "123"))
        self.label_3.setText(_translate("MainWindow", "LOGIN NAME"))
    def FcConnectToSQL(self):
        # print('Server Name:', self.InputBox_ServerName.toPlainText()) # Test Function
        print("Driver={SQL Server Native Client 11.0};"
                       "Server=", self.InputBox_ServerName.toPlainText() ,";"
                       "Database=", self.InputBox_DatabaseName.toPlainText() ,";"
                       "Trusted_Connection=yes;")
        
# import pyodbc 
# cnxn = pyodbc.connect("Driver={SQL Server Native Client 11.0};"
#                       "Server=server_name;"
#                       "Database=db_name;"
#                       "Trusted_Connection=yes;")

# cursor = cnxn.cursor()
# cursor.execute('SELECT * FROM Table')

# for row in cursor:
#     print('row = %r' % (row,))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
